Add custom event_time column as an option during baseline creation
snowflakedb/SnowAlert pull request #448
Opened 2020-10-19 23:34 UTC by sfc-gh-pkommini

- Adds default options for custom temporal column named field to allow for easier baselining of tables in webUI
- Add logic to accept the custom temporal column for the table and uses it in the generated SQL
- Add additional files and dirs to `.gitignore`

2020-10-20 18:03 UTC, sfc-gh-afedorov requested changes
please test & describe testing in change description.

what does error look like if someone forgets `:` in the field?

2020-10-20 18:29 UTC, sfc-gh-afedorov commented on .gitignore
> +dist/
gotcha -- looks like I mis-remembered, in node that's result of "Nuxt.js build", not standard

in Python, it's standard when you build something to distribute via, e.g. pypi? open to building towards this, as at least @sfc-gh-gbutzi has been interested in re-using pieces of the code we wrote in other scripts, but this seems like something we'd want to do in a separate design doc (with Greg's team giving feedback) and then in a separate PR.

2020-10-20 21:13 UTC, sfc-gh-pkommini commented on .gitignore
> +dist/
Reverted the gitignore file.

2020-10-21 03:21 UTC, sfc-gh-pkommini commented
Added screenshot of how the `:` not being present is handled.

2020-10-21 04:22 UTC, merged