AWS_Cloudtrail_pack
snowflakedb/SnowAlert pull request #491
Opened 2021-02-24 07:19 UTC by sfc-gh-srathod

Please review the aws_cloudtrail sql pack

2021-03-03 01:42 UTC, anfedorov requested changes
good start, but there's a few pieces left before we can test this

2021-03-03 01:42 UTC, anfedorov commented on packs/AWS_CloudTrail.sql
> +-- varmap:
please update header to include params definition

2021-03-03 01:42 UTC, anfedorov commented on packs/AWS_CloudTrail.sql
> +CREATE SEQUENCE IF NOT EXISTS LANDING_TABLE_SEQ START 1 INCREMENT 1;
let's keep the casing consistent -- we want our names to be lower case, so `LANDING_TABLE_SEQ` should be, as well, to separate it from the language constructs

2021-03-03 01:42 UTC, anfedorov commented on packs/AWS_CloudTrail.sql
> +    COPY INTO {staging_table(v)}
this is not a valid param

2021-04-08 04:27 UTC, sfc-gh-afedorov commented
now in https://github.com/snowflakedb/snowsql-pack/tree/main/aws_cloudtrail

2021-04-08 04:27 UTC, closed without merging