added table, api method spec and api call to detect public ebs snapshots
snowflakedb/SnowAlert pull request #527
Opened 2021-04-14 11:30 UTC by sfc-gh-gkadam

[Blusec-385 Detect public EBS snapshots] (https://snowflakecomputing.atlassian.net/browse/BLUSEC-385)
Added table name as - `'ebs_describe_snapshot'` in supplementary tables
Added API method spec name - `'ebs.describe_snapshot'`
added `'ebs.describe_snapshot'` under collect apis

2021-04-15 15:05 UTC, sfc-gh-dwyleczukstern commented
@sfc-gh-afedorov It looks like the PR is failing because whitesource is complaining that SnowAlert is using out of date libraries. Is that assessment correct? Should we submit a separate PR to update those libraries?

2021-04-15 18:16 UTC, sfc-gh-afedorov commented
not immediately sure why this is failing but v1.10.0 should be up-to-date with Whitesource requirements -- https://github.com/snowflakedb/SnowAlert/runs/2345087173

almost done fixing / testing this, would you like the changes merged in, or as comments to understand them better going forward?

2021-04-15 19:13 UTC, sfc-gh-afedorov requested changes
wish we had this documented better. let me know if you'd like my version of the code or to apply these changes yourself.

there's also a script in `./migrations` that needs to be updated with the `CREATE TABLE` command

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +    'ebs_describe_snapshot': [
it's plural and this is ec2 API not ebs, so `ec2_describe_snapshots`

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +        ('recorded_at', 'TIMESTAMP_LTZ'),
this has a region, so the top rows should be `recorded_at` `account_id` `region` `error`

the rest of the rows should be in the same order as in the docs

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +        ('next_token', 'STRING'),
`next_token` is handled by the driver and not part of the response array

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +            'DescribeSnapshot': {
the response has a single array `Snapshot` of items we want to load, so this code should be `'Snapshot': [...]`

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +                'KmsKeyID': 'kmskeyid',
camel case should turn to snake case, i.e. `kms_key_id` here and above

order should be same as in docs

2021-04-15 19:13 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +            'ebs.describe_snapshot',
the API being ingested is `ec2 describe-snapshots`, so this should be `ec2.describe_snapshots`

2021-04-19 06:00 UTC, sfc-gh-gkadam commented
I have made the request changes still am seeing the "Changes Requested" tab. @sfc-gh-afedorov

2021-04-20 15:08 UTC, sfc-gh-afedorov reviewed
close! please double check that we are using all of the responses in [the docs](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-snapshots.html#output)

2021-04-20 15:08 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +            'Snapshot': {
because the `Snapshots` returned by AWS is a list, you need to use a list `[...]` instead of a dict `{...}` here.

2021-04-20 15:08 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +        ('description', 'STRING'),
the first data column should be `data_encryption_key_id`, to store the `DataEncryptionKeyId` key in the response from AWS

2021-04-20 15:08 UTC, sfc-gh-afedorov commented on src/connectors/aws_collect.py
> +    # https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-snapshots.html
link directly to the output section of the page, as the others do — https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-snapshots.html#output

2021-04-20 16:40 UTC, sfc-gh-afedorov commented on migrations/v1_9_6-v1_10_0.md
> +## EC2 DESCRIBE SNAPSHOTS
please upper case acronyms, but title-case the titles, i.e. "EC2 Describe Snapshots"

2021-04-20 16:50 UTC, sfc-gh-afedorov approved these changes

2021-04-20 16:53 UTC, merged